#!/bin/sh

set -ev

cd $(dirname $0)/data
curl -L -o dicomifier-data.zip --silent --show-error \
  https://iris.icube.unistra.fr/nextcloud/s/qGD3XgXoLbF9D8w/download
unzip -q dicomifier-data.zip
rm dicomifier-data.zip
