#!/bin/sh

cd $(dirname $0)
curl -L -o dicomifier-data.zip https://iris.icube.unistra.fr/nextcloud/s/qGD3XgXoLbF9D8w/download
unzip -q dicomifier-data.zip
mv dicomifier-data/* ./data/
rmdir dicomifier-data/
rm dicomifier-data.zip
