#!/bin/bash

set -v

source "$HOME/miniconda/etc/profile.d/conda.sh"
conda activate dicomifier

export WORKSPACE=${WORKSPACE:?}
export BUILD_DIR="${WORKSPACE}/${BUILD_DIR:-build}"
export INSTALL_DIR="${WORKSPACE}/${INSTALL_DIR:-install}"

PYTHON=$(awk -F= '$0 ~ /^PYTHON_EXECUTABLE:/ { print $2 }' ${BUILD_DIR}/CMakeCache.txt)

export LD_LIBRARY_PATH=${INSTALL_DIR}/lib
export PYTHONPATH=${INSTALL_DIR}/$(${PYTHON} -c "from distutils.sysconfig import *; print(get_python_lib(True, prefix=''))")

export DICOMIFIER_TEST_DATA=${WORKSPACE}/tests/data

cd "${BUILD_DIR}"

RETURNCODES=()

ctest -T Test
RETURNCODES[${#RETURNCODES[*]}]=$?

${PYTHON} -m unittest discover -v -s ${WORKSPACE}/tests/python/
RETURNCODES[${#RETURNCODES[*]}]=$?

if [ -z "${DICOMIFIER_SKIP_CONVERSION_TESTS}" ]; then
  cd ${WORKSPACE}
  if [ ! -d tests/data/input ]; then
    ./tests/download_data
  fi
  export PATH=${INSTALL_DIR}/bin:${PATH}

  ${PYTHON} ./tests/diff/to_dicom.py
  RETURNCODES[${#RETURNCODES[*]}]=$?

  ${PYTHON} ./tests/diff/to_nifti.py
  RETURNCODES[${#RETURNCODES[*]}]=$?

  ${PYTHON} ./tests/diff/list.py
  RETURNCODES[${#RETURNCODES[*]}]=$?
fi

conda remove --name dicomifier --all

RETURNCODE=$(printf "%s\n" ${RETURNCODES[*]} | sort -n | tail -n 1)
exit ${RETURNCODE}
