#!/bin/sh

set -ev

export WORKSPACE=${WORKSPACE:?}
export BUILD_DIR="${WORKSPACE}/${BUILD_DIR:-build}"
export INSTALL_DIR="${WORKSPACE}/${INSTALL_DIR:-install}"

mkdir -p ${BUILD_DIR}
mkdir -p ${INSTALL_DIR}

cd ${BUILD_DIR}

cmake \
  -G Ninja \
  -D CMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
  -D PYTHON_EXECUTABLE=/usr/local/bin/python3 \
  -D ICU_ROOT=/usr/local/opt/icu4c/ \
  ${CMAKE_OPTIONS} \
  ..
cmake --build . --target install
