#!/bin/sh

set -ev

export PYTHON=${PYTHON:-python}

export HOMEBREW_NO_INSTALL_CLEANUP=1

# WARNING The Python environment in Travis is weird: "brew install python" fails
# when symlinking, due to the presence of python@2.
brew upgrade python || brew install python || true
brew link --overwrite python || true

for PACKAGE in boost cmake ninja pkg-config pybind11; do
    VERSIONS=$(brew ls --versions ${PACKAGE} || true)
    if [ -z "${VERSIONS}" ]; then
        COMMAND="install"
    else
        OUTDATED=$(brew outdated ${PACKAGE} || true)
        if [ -z "${OUTDATED}" ]; then
            COMMAND=""
        else
            COMMAND="upgrade"
        fi
    fi
    
    if [ -n "${COMMAND}" ]; then
        brew ${COMMAND} ${PACKAGE}
    fi
done

python3 -m pip install --upgrade nibabel numpy dateutil

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $HOME/miniconda
source $HOME/miniconda/bin/activate
conda init
hash -r

conda update -q conda
conda install -c conda-forge odil 
