#!/bin/sh

set -e

DIR="/usr/lib/python2.7/dist-packages/dicomifier"

case "$1" in
    configure)
        ldconfig
        python -c 'import sys, compileall ; exit_status = int(not compileall.main()); sys.exit(exit_status)' -q $DIR
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        python -c 'import sys, compileall ; exit_status = int(not compileall.main()); sys.exit(exit_status)' -q $DIR
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
