#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

if [ "${Python}" = "2" ]
then
  PYTHON_VERSION="$(pyversions -dv)"
elif [ "${Python}" = "3" ]
then
  PYTHON_VERSION="$(py3versions -dv)"
else
  PYTHON_VERSION="UNKOWN"
fi

cd ${WORKSPACE}

mkdir build${POSTFIX}
mkdir install${POSTFIX}
cd build${POSTFIX}
cmake \
  -DPython_ADDITIONAL_VERSIONS=${PYTHON_VERSION} \
  -DPYTHON_EXECUTABLE=/usr/bin/python${PYTHON_VERSION} \
  -DCMAKE_INSTALL_PREFIX="${WORKSPACE}/install${POSTFIX}" \
  ${CMAKE_OPTIONS} \
  ..
make ${MAKE_OPTIONS} install
