#!/bin/sh

set -ev

apt-get update
apt-get -y --no-install-recommends install gnupg software-properties-common wget

REPOSITORY=http://dl.bintray.com/lamyj/generic
wget -O - ${REPOSITORY}/gpg.key | apt-key add -
if wget -q -O /dev/null ${REPOSITORY}/apt/dists/$(lsb_release -cs)/Release; then
  add-apt-repository "deb ${REPOSITORY}/apt $(lsb_release -cs) main"
fi
apt-get update

apt-get -y --no-install-recommends install \
  build-essential cmake ninja-build pkg-config python3 \
  libboost-dev libboost-date-time-dev libboost-exception-dev \
  libboost-filesystem-dev libboost-regex-dev libboost-system-dev zlib1g-dev \
  pybind11-dev python3-pybind11 python3-dev \
  python3-dateutil python3-nibabel python3-numpy python3-odil python3-requests \
  libboost-test-dev
