#!/bin/sh

set -ev

apt-get update
apt-get -y --no-install-recommends install gnupg software-properties-common wget

REPOSITORY=http://dl.bintray.com/lamyj/generic
wget -O - ${REPOSITORY}/gpg.key | apt-key add -
echo "deb ${REPOSITORY}/apt $(lsb_release -cs) main" >> /etc/apt/sources.list

apt-get update

# Compilation toolchain
PACKAGES="build-essential cmake pkg-config python-minimal"
# Dependencies of C++ lib
PACKAGES="${PACKAGES} libboost-date-time-dev libboost-filesystem-dev "
PACKAGES="${PACKAGES} libboost-regex-dev libboost-system-dev "
PACKAGES="${PACKAGES} liblog4cpp5-dev zlib1g-dev"
# Dependencies of Python lib
PACKAGES="${PACKAGES} python3-dateutil"
PACKAGES="${PACKAGES} python3-dev python3-nibabel"
PACKAGES="${PACKAGES} python3-numpy python3-odil"
# Dependencies of tests
PACKAGES="${PACKAGES} libboost-test-dev unzip"

apt-get -y --no-install-recommends install ${PACKAGES}
