#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

if [ "${Python}" = "2" ]
then
  export NOSE="nosetests-2.7"
elif [ "${Python}" = "3" ]
then
  export NOSE="nosetests3"
fi

export LD_LIBRARY_PATH=${WORKSPACE}/install${POSTFIX}/lib
export PYTHONPATH=${WORKSPACE}/install${POSTFIX}/$(python${Python} -c "from distutils.sysconfig import *; print(get_python_lib(True, prefix=''))")

cd ${WORKSPACE}/build${POSTFIX}

"${WORKSPACE}/tests/run_tests.sh"

cd ${HOME}
# WARNING: 467 MB archived, 807 MB unzipped
wget -qO - https://github.com/fli-iam/dicomifier-data/archive/master.tar.gz ⁠\
  | tar -x -z -f -

export PATH=${WORKSPACE}/install${POSTFIX}/bin:${PATH}
python${Python} ./dicomifier-data-master/scripts/diff_bruker2dicom.py
python${Python} ./dicomifier-data-master/scripts/diff_dicom2nifti.py

rm -rf dicomifier-data-master
