#!/bin/sh

set -ev

export Python=${Python:?}
export WORKSPACE=${WORKSPACE:?}

if [ "${Python}" = "2" ]
then
  export NOSE="nosetests-2.7"
elif [ "${Python}" = "3" ]
then
  export NOSE="nosetests3"
fi

export LD_LIBRARY_PATH=${WORKSPACE}/install${POSTFIX}/lib
export PYTHONPATH=${WORKSPACE}/install${POSTFIX}/$(python${Python} -c "from distutils.sysconfig import *; print(get_python_lib(True, prefix=''))")

cd ${WORKSPACE}/build${POSTFIX}

"${WORKSPACE}/tests/run_tests.sh"
